[project]
name = "fishtest-worker"
version = "0.1.0"
description = "fishtest-worker"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "openlock>=1.1.5",
    "requests>=2.25.1",
    "simpleeval>=0.9.13",
]
